services:
  - type: web
    name: instantmingle
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: SECRET_KEY
        value: 6Ldy5gIqAAAAAB7ZRuoZjfviwVhU97hULJp5BJw_
